# In google colab

In [1]:
# !git clone https://github.com/Thanh-Thanh-Thanh/thanh.git
# !pip install -r /content/thanh/requirements.txt

In [2]:
# from google.colab import drive
# drive.mount('/content/drive')

# Import lib

In [3]:
import os
if os.getenv("CUDA_VISIBLE_DEVICES") is None:
    gpu_num = 0 # Use "" to use the CPU
    os.environ["CUDA_VISIBLE_DEVICES"] = f"{gpu_num}"
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'

# Import Sionna
import sys
sys.path.append('../') # comment if workspace
# sys.path.append('/content/thanh') # if colab
import sionna

# try:
#     import sionna
# except ImportError as e:
#     # Install Sionna if package is not already installed
#     import os
#     os.system("pip install sionna")
#     import sionna

import tensorflow as tf
# Configure the notebook to use only a single GPU and allocate only as much memory as needed
# For more details, see https://www.tensorflow.org/guide/gpu
gpus = tf.config.list_physical_devices('GPU')
if gpus:
    try:
        tf.config.experimental.set_memory_growth(gpus[0], True)
    except RuntimeError as e:
        print(e)
# Avoid warnings from TensorFlow
tf.get_logger().setLevel('ERROR')

sionna.config.seed = 42 # Set seed for reproducible results

# Load the required Sionna components
from sionna.nr import PUSCHConfig, PUSCHTransmitter, PUSCHReceiver, CarrierConfig, PUSCHDMRSConfig,\
                        TBConfig, PUSCHPilotPattern, TBEncoder, PUSCHPrecoder, LayerMapper, LayerDemapper, check_pusch_configs,\
                        TBDecoder, PUSCHLSChannelEstimator
from sionna.nr.utils import generate_prng_seq, select_mcs, calculate_tb_size
from sionna.channel import AWGN, RayleighBlockFading, OFDMChannel, TimeChannel, time_lag_discrete_time_channel
from sionna.channel.utils import *
from sionna.channel.tr38901 import Antenna, AntennaArray, UMi, UMa, RMa, TDL, CDL
from sionna.channel import gen_single_sector_topology as gen_topology
from sionna.utils import compute_ber, ebnodb2no, sim_ber, array_to_hash, create_timestamped_folders, b2b, f2f, \
    BinarySource, config_parser, fft_size_return
from sionna.ofdm import KBestDetector, LinearDetector, MaximumLikelihoodDetector,\
        LSChannelEstimator, LMMSEEqualizer, RemoveNulledSubcarriers, ResourceGridDemapper,\
        ResourceGrid, ResourceGridMapper, OFDMModulator
from sionna.mimo import StreamManagement
from sionna.mapping import Mapper, Demapper
from sionna.fec.ldpc import LDPC5GEncoder

from sionna.nr.my_abc import *

In [4]:
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import time
from datetime import datetime, timedelta
# from bs4 import BeautifulSoup
import pickle
from collections import namedtuple
import json
from tqdm import tqdm
import itertools
import io
import h5py
import random

## A Hello World Example

Let us start with a simple "Hello, World!" example in which we will simulate PUSCH transmissions from a single transmitter to a single receiver over an AWGN channel.

In [5]:
# from dataclasses import dataclass, field
# from typing import List

# @dataclass
# class SystemConfig:
#     NCellId: int = 246
#     FrequencyRange: int = 1
#     BandWidth: int = 100
#     Numerology: int = 1
#     CpType: int = 0
#     NTxAnt: int = 1
#     NRxAnt: int = 8
#     BwpNRb: int = 273
#     BwpRbOffset: int = 0
#     harqProcFlag: int = 0
#     nHarqProc: int = 1
#     rvSeq: int = 0


# @dataclass
# class UeConfig:
#     TransformPrecoding: int = 0
#     Rnti: int = 20002
#     nId: int = 246
#     CodeBookBased: int = 0
#     DmrsPortSetIdx: List[int] = field(default_factory=lambda: [0])  # FIXED
#     NLayers: int = 1
#     NumDmrsCdmGroupsWithoutData: int = 2
#     Tpmi: int = 0
#     FirstSymb: int = 0
#     NPuschSymbAll: int = 14
#     RaType: int = 1
#     FirstPrb: int = 31
#     NPrb: int = 4
#     FrequencyHoppingMode: int = 0
#     McsTable: int = 0
#     Mcs: int = 3
#     ILbrm: int = 0
#     nScId: int = 0
#     NnScIdId: int = 246
#     DmrsConfigurationType: int = 0
#     DmrsDuration: int = 1
#     DmrsAdditionalPosition: int = 1
#     PuschMappingType: int = 0
#     DmrsTypeAPosition: int = 3
#     HoppingMode: int = 0
#     NRsId: int = 0
#     Ptrs: int = 0
#     ScalingFactor: int = 0
#     OAck: int = 0
#     IHarqAckOffset: int = 11
#     OCsi1: int = 0
#     ICsi1Offset: int = 7
#     OCsi2: int = 0
#     ICsi2Offset: int = 0
#     NPrbOh: int = 0
#     nCw: int = 1
#     TpPi2Bpsk: int = 0

# @dataclass
# class MyConfig:
#     Sys: SystemConfig
#     Ue: List[UeConfig]
#     Num_tx: int = 1
#     Num_rx: int = 1
#     Carrier_frequency: float = 2.55e9  # Carrier frequency in Hz

# # Example usage
# My_Config = MyConfig(SystemConfig(), [UeConfig()])


In [6]:
# class MyPUSCHConfig(PUSCHConfig):
#     def __init__(self, My_Config: MyConfig):
#         self.My_Config = My_Config
#         super().__init__(
#             carrier_config=CarrierConfig(
#                 n_cell_id=My_Config.Sys.NCellId,
#                 cyclic_prefix="normal" if ~My_Config.Sys.CpType else "extended",
#                 subcarrier_spacing=15*(2**My_Config.Sys.Numerology),
#                 n_size_grid=My_Config.Sys.BwpNRb,
#                 n_start_grid=My_Config.Sys.BwpRbOffset,
#                 slot_number=4,
#                 frame_number=0
#             ),
#             pusch_dmrs_config=PUSCHDMRSConfig(
#                 config_type=My_Config.Ue[0].DmrsConfigurationType + 1,
#                 length=My_Config.Ue[0].DmrsDuration,
#                 additional_position=My_Config.Ue[0].DmrsAdditionalPosition,
#                 dmrs_port_set=My_Config.Ue[0].DmrsPortSetIdx,
#                 n_id=My_Config.Ue[0].NnScIdId,
#                 n_scid=My_Config.Ue[0].nScId,
#                 num_cdm_groups_without_data=My_Config.Ue[0].NumDmrsCdmGroupsWithoutData,
#                 type_a_position=My_Config.Ue[0].DmrsTypeAPosition
#             ),
#             tb_config=TBConfig(
#                 channel_type='PUSCH',
#                 n_id=My_Config.Ue[0].nId,
#                 mcs_table=My_Config.Ue[0].McsTable + 1,
#                 mcs_index=My_Config.Ue[0].Mcs
#             ),
#             mapping_type='A' if ~My_Config.Ue[0].PuschMappingType else 'B',
#             n_size_bwp=My_Config.Sys.BwpNRb,
#             n_start_bwp=My_Config.Sys.BwpRbOffset,
#             num_layers=My_Config.Ue[0].NLayers,
#             num_antenna_ports=len(My_Config.Ue[0].DmrsPortSetIdx),
#             precoding='non-codebook' if ~My_Config.Ue[0].CodeBookBased else 'codebook',
#             tpmi=My_Config.Ue[0].Tpmi,
#             transform_precoding=False if ~My_Config.Ue[0].TransformPrecoding else True,
#             n_rnti=My_Config.Ue[0].Rnti,
#             symbol_allocation=[My_Config.Ue[0].FirstSymb,My_Config.Ue[0].NPuschSymbAll]
#         )
#     @property
#     def first_resource_block(self):
#         """
#         :class:`~sionna.nr.CarrierConfig` : Carrier configuration
#         """
#         return self.My_Config.Ue[0].FirstPrb

#     @property
#     def first_subcarrier(self):
#         """
#         :class:`~sionna.nr.CarrierConfig` : Carrier configuration
#         """
#         return 12*self.first_resource_block

#     @property
#     def num_resource_blocks(self):
#         """
#         int, read-only : Number of allocated resource blocks for the
#             PUSCH transmissions.
#         """
#         return self.My_Config.Ue[0].NPrb

#     @property
#     def dmrs_grid(self):
#         # pylint: disable=line-too-long
#         """
#         complex, [num_dmrs_ports, num_subcarriers, num_symbols_per_slot], read-only : Empty
#             resource grid for each DMRS port, filled with DMRS signals

#             This property returns for each configured DMRS port an empty
#             resource grid filled with DMRS signals as defined in
#             Section 6.4.1.1 [3GPP38211]. Not all possible options are implemented,
#             e.g., frequency hopping and transform precoding are not available.

#             This property provides the *unprecoded* DMRS for each configured DMRS port.
#             Precoding might be applied to map the DMRS to the antenna ports. However,
#             in this case, the number of DMRS ports cannot be larger than the number of
#             layers.
#         """
#         # Check configuration
#         self.check_config()

#         # Configure DMRS ports set if it has not been set
#         reset_dmrs_port_set = False
#         if len(self.dmrs.dmrs_port_set)==0:
#             self.dmrs.dmrs_port_set = list(range(self.num_layers))
#             reset_dmrs_port_set = True

#         # Generate empty resource grid for each port
#         a_tilde = np.zeros([len(self.dmrs.dmrs_port_set),
#                             self.num_subcarriers,
#                             self.carrier.num_symbols_per_slot],
#                             dtype=complex)
#         first_subcarrier = self.first_subcarrier
#         num_subcarriers = self.num_subcarriers

#         # For every l_bar
#         for l_bar in self.l_bar:

#             # For every l_prime
#             for l_prime in self.l_prime:

#                 # Compute c_init
#                 l = l_bar + l_prime
#                 c_init = self.c_init(l)
#                 # Generate RNG
#                 c = generate_prng_seq(first_subcarrier + num_subcarriers, c_init=c_init)
#                 c = c[first_subcarrier:]

#                 # Map to QAM
#                 r = 1/np.sqrt(2)*((1-2*c[::2]) + 1j*(1-2*c[1::2]))

#                 # For every port in the dmrs port set
#                 for j_ind, _ in enumerate(self.dmrs.dmrs_port_set):

#                     # For every n
#                     for n in self.n:

#                         # For every k_prime
#                         for k_prime in [0, 1]:

#                             if self.dmrs.config_type==1:
#                                 k = 4*n + 2*k_prime + \
#                                     self.dmrs.deltas[j_ind]
#                             else: # config_type == 2
#                                 k = 6*n + k_prime + \
#                                     self.dmrs.deltas[j_ind]

#                             a_tilde[j_ind, k, self.l_ref+l] = \
#                                 r[2*n + k_prime] * \
#                                 self.dmrs.w_f[k_prime][j_ind] * \
#                                 self.dmrs.w_t[l_prime][j_ind]

#         # Amplitude scaling
#         a = self.dmrs.beta*a_tilde

#         # Reset DMRS port set if it was not set
#         if reset_dmrs_port_set:
#             self.dmrs.dmrs_port_set = []

#         return a
# My_Config = MyConfig(SystemConfig(), [UeConfig()])
# Pusch_Config = MyPUSCHConfig(My_Config)
# Pusch_Config.show()

In [7]:
"""
frame_number, n_cell_id: No change
n_rnti, tb.n_id: Change in tb_encoder, but not in dmrs (same c -> same x)
slot_number, dmrs.n_id, dmrs.n_scid, mcs: No change in tb_encoder (same b -> same c), but in dmrs
"""

'\nframe_number, n_cell_id: No change\nn_rnti, tb.n_id: Change in tb_encoder, but not in dmrs (same c -> same x)\nslot_number, dmrs.n_id, dmrs.n_scid, mcs: No change in tb_encoder (same b -> same c), but in dmrs\n'

In [8]:
# PuschRecord = namedtuple("PuschRecord", [
#     "nSFN", "nSlot", "nPDU", "nGroup", "nUlsch", "nUlcch", "nRachPresent",
#     "nRNTI", "nUEId", "nBWPSize", "nBWPStart", "nSubcSpacing", "nCpType", "nULType",
#     "nMcsTable", "nMCS", "nTransPrecode", "nTransmissionScheme", "nNrOfLayers",
#     "nPortIndex", "nNid", "nSCID", "nNIDnSCID", "nNrOfAntennaPorts",
#     "nVRBtoPRB", "nPMI", "nStartSymbolIndex", "nNrOfSymbols", "nResourceAllocType",
#     "nRBStart", "nRBSize", "nTBSize", "nRV", "nHARQID", "nNDI", "nMappingType",
#     "nDMRSConfigType", "nNrOfCDMs", "nNrOfDMRSSymbols", "nDMRSAddPos",
#     "nPTRSPresent", "nAck", "nAlphaScaling", "nBetaOffsetACKIndex", "nCsiPart1",
#     "nBetaOffsetCsiPart1Index", "nCsiPart2", "nBetaOffsetCsiPart2Index",
#     "nTpPi2BPSK", "nTPPuschID", "nRxRUIdx", "nUE", "nPduIdx",

#     # New fields for channel and filenames
#     "Dmrs_mask",
#     "Channel_model", "Speed", "Delay_spread", "Esno_db",
#     "Data_filename","Data_dirname"
#     ]
# )

# def save_pickle(data, parent_name, group_name):
#     """Saves data to a pickle file."""
#     def save_to_pickle(data, filename):
#         with open(filename, "wb") as f:
#             pickle.dump(data, f)
#     b, c, y = data
#     save_to_pickle(b.numpy(), f'{parent_name}/{group_name}.b.pkl')
#     save_to_pickle(c.numpy(), f'{parent_name}/{group_name}.c.pkl')
#     save_to_pickle(y.numpy(), f'{parent_name}/{group_name}.y.pkl')

# def save_hdf5(data, parent_name, group_name):
#     b, c, y = data
#     with h5py.File(f"{parent_name}.hdf5", "a") as hf:
#         hf.create_dataset(f"{group_name}_b", data=b.numpy())
#         hf.create_dataset(f"{group_name}_c", data=c.numpy())
#         hf.create_dataset(f"{group_name}_y", data=y.numpy())


In [9]:
# # class MySimulator():
# #     def __init__(self, pusch_config: MyPUSCHConfig):

# #         self.Num_rx = pusch_config.My_Config.Num_rx
# #         self.Num_tx = pusch_config.My_Config.Num_tx
    
# #         tb_size = pusch_config.tb_size
# #         num_coded_bits = pusch_config.num_coded_bits
# #         target_coderate = pusch_config.tb.target_coderate
# #         num_bits_per_symbol = pusch_config.tb.num_bits_per_symbol

# #         num_layers = pusch_config.num_layers
# #         n_rnti = pusch_config.n_rnti
# #         n_id = pusch_config.tb.n_id

# #         self.Binary_Source = BinarySource(dtype=tf.float32)
# #         self.TB_Encoder = TBEncoder(target_tb_size=tb_size,
# #                             num_coded_bits=num_coded_bits,
# #                             target_coderate=target_coderate,
# #                             num_bits_per_symbol=num_bits_per_symbol,
# #                             num_layers=num_layers,
# #                             n_rnti=n_rnti,
# #                             n_id=n_id,
# #                             channel_type="PUSCH",
# #                             codeword_index=0,
# #                             use_scrambler=True,
# #                             verbose=False,
# #                             output_dtype=tf.float32)
        
# #         self.Constellation_Mapper = Mapper("qam", num_bits_per_symbol, dtype=tf.complex64)

# #         self.Layer_Mapper = LayerMapper(num_layers=num_layers, dtype=tf.complex64)
    
# #         self.Pilot_Pattern = PUSCHPilotPattern([pusch_config], dtype=tf.complex64)

# #         num_subcarriers = pusch_config.num_subcarriers
# #         subcarrier_spacing = pusch_config.carrier.subcarrier_spacing*1e3
# #         fft_size = num_subcarriers
# #         cp_length = min(num_subcarriers, 288)
# #         guard_subcarriers = (0,0)
# #         # Define the resource grid.
# #         resource_grid = ResourceGrid(
# #             num_ofdm_symbols=14,
# #             fft_size=fft_size,
# #             subcarrier_spacing=subcarrier_spacing,
# #             num_tx=self.Num_tx,
# #             num_streams_per_tx=1,
# #             cyclic_prefix_length=cp_length,
# #             num_guard_carriers=guard_subcarriers,
# #             dc_null=False,
# #             pilot_pattern=self.Pilot_Pattern,
# #             dtype=tf.complex64
# #         )

# #         self.Resource_Grid_Mapper = ResourceGridMapper(resource_grid, dtype=tf.complex64)        
        
# #         self.AWGN = AWGN()

 
# #         self.Channel_Estimator = PUSCHLSChannelEstimator(
# #                         resource_grid,
# #                         pusch_config.dmrs.length,
# #                         pusch_config.dmrs.additional_position,
# #                         pusch_config.dmrs.num_cdm_groups_without_data,
# #                         interpolation_type='nn',
# #                         dtype=tf.complex64)

# #         rxtx_association = np.ones([self.Num_rx, self.Num_tx], bool)
# #         stream_management = StreamManagement(rxtx_association, pusch_config.num_layers)
# #         self.Mimo_Detector = LinearDetector("lmmse", "bit", "maxlog", resource_grid, stream_management,
# #                                     "qam", pusch_config.tb.num_bits_per_symbol, dtype=tf.complex64)
        

# #         self.Layer_Demapper = LayerDemapper(self.Layer_Mapper, num_bits_per_symbol=num_bits_per_symbol)
# #         self.TB_Decode = TBDecoder(self.TB_Encoder, output_dtype=tf.float32)

# #         self.tb_size = tb_size
# #         self.resource_grid = resource_grid
# #         self.pusch_config = pusch_config
        
# #     def update_pilots(self, pilots):
# #         self.Resource_Grid_Mapper._resource_grid.pilot_pattern.pilots = pilots

# #         self.Channel_Estimator = PUSCHLSChannelEstimator(
# #                         self.Resource_Grid_Mapper._resource_grid,
# #                         self.pusch_config.dmrs.length,
# #                         self.pusch_config.dmrs.additional_position,
# #                         self.pusch_config.dmrs.num_cdm_groups_without_data,
# #                         interpolation_type='nn',
# #                         dtype=tf.complex64)

# #         rxtx_association = np.ones([self.Num_rx, self.Num_tx], bool)
# #         stream_management = StreamManagement(rxtx_association, self.pusch_config.num_layers)
# #         self.Mimo_Detector = LinearDetector("lmmse", "bit", "maxlog", self.Resource_Grid_Mapper._resource_grid, stream_management,
# #                                     "qam", self.pusch_config.tb.num_bits_per_symbol, dtype=tf.complex64)

# #     def sim(self, batch_size, channel_model, no_scaling, from_binary_source=True, gen_seed=2004*10+4):
# #         if from_binary_source:
# #             b = self.Binary_Source([batch_size, self.Num_tx, self.tb_size])
# #         else:
# #             b = tf.reshape(tf.constant(generate_prng_seq(batch_size * self.Num_tx * self.tb_size, gen_seed), dtype=tf.float32), [batch_size, self.Num_tx, self.tb_size])
# #         c = self.TB_Encoder(b)
# #         x_map = self.Constellation_Mapper(c)
# #         x_layer = self.Layer_Mapper(x_map)
# #         x = self.Resource_Grid_Mapper(x_layer)

# #         y, h = channel_model(x)
# #         no = no_scaling * tf.math.reduce_variance(y)

# #         y = self.AWGN([y, no])
        
# #         return b, c, y
    
# #     def rec(self, y):
# #         no_ = 0.001
# #         h_hat, err_var = self.Channel_Estimator([y, no_])
# #         llr_det = self.Mimo_Detector([y, h_hat, err_var, no_])
# #         llr_layer = self.Layer_Demapper(llr_det)
# #         b_hat, tb_crc_status = self.TB_Decode(llr_layer)

# #         return b_hat, llr_det, tb_crc_status

# ue_antenna = Antenna(polarization="single",
#                 polarization_type="V",
#                 antenna_pattern="38.901",
#                 carrier_frequency=2.55e9)

# gnb_array = AntennaArray(num_rows=1,
#                         num_cols=8//2,
#                         polarization="dual",
#                         polarization_type="cross",
#                         antenna_pattern="38.901",
#                         carrier_frequency=2.55e9)

# channel_model = CDL(model = 'C',
#                             delay_spread = 150*1e-9,
#                             carrier_frequency = 2.55e9,
#                             ut_array = ue_antenna,
#                             bs_array = gnb_array,
#                             direction = 'uplink',
#                             min_speed = 1,
#                             max_speed = 1)
# simulator = MySimulator(Pusch_Config)

# channel = OFDMChannel(channel_model=channel_model, resource_grid=simulator.resource_grid,
#                                     add_awgn=False, normalize_channel=True, return_channel=True)



In [10]:
# %timeit b, c, y, h = simulator.sim(1, channel, 0.5, True); _,_,crc = simulator.rec(y); print(crc)

In [ ]:
def generate_data(name: str,
        data_dir: str,
        pusch_configs: List[MyPUSCHConfig],
        channel_scenarios: List[str],
        esno_dbs: List[float],
        slots: List[int],
        save_dataset: str = None):
    assert save_dataset in [None, 'hdf5', 'pickle']
    """set up save directory"""
    pusch_records=[]
    parquet_dir = f'{data_dir}/parquet'
    if save_dataset: os.makedirs(parquet_dir, exist_ok=True)
    hdf5_dir = f'{data_dir}/hdf5'
    if save_dataset == 'hdf5': os.makedirs(hdf5_dir, exist_ok=True)
    pickle_dir = f'{data_dir}/pickle'
    if save_dataset == 'pickle': os.makedirs(pickle_dir, exist_ok=True)

    """set up for per slot"""
    len_per_case = len(slots)

    total_iterations = len(pusch_configs) * len(esno_dbs) * len_per_case


    """generate ..."""
    with tqdm(total=total_iterations, desc="Generating Data") as pbar:
        for config_idx, pusch_config in enumerate(pusch_configs):
            # num_rx = pusch_config.My_Config.Num_rx # 1
            # num_tx = pusch_config.My_Config.Num_tx # 1
            # num_streams_per_tx = pusch_config.num_antenna_ports # 1
           
            Pusch_Pilots = {}
            Pusch_Slots = [4,5,14,15]
            for n, slot in enumerate(Pusch_Slots):
                pusch_config_i = pusch_config.clone()
                pusch_config_i.carrier.slot_number = slot
                pilot_pattern_i = PUSCHPilotPattern([pusch_config_i], dtype=tf.complex64)
                Pusch_Pilots[slot] = pilot_pattern_i.pilots
            len_pusch = len(Pusch_Slots)

            """set up for all case"""
            carrier_frequency = pusch_config.My_Config.Carrier_frequency
            num_rx_ant = pusch_config.My_Config.Sys.NRxAnt

            ue_antenna = Antenna(polarization="single",
                            polarization_type="V",
                            antenna_pattern="38.901",
                            carrier_frequency=carrier_frequency)

            gnb_array = AntennaArray(num_rows=1,
                                    num_cols=num_rx_ant//2,
                                    polarization="dual",
                                    polarization_type="cross",
                                    antenna_pattern="38.901",
                                    carrier_frequency=carrier_frequency)


            simulator = MySimulator(pusch_config)

            channel_scenario = random.choice(channel_scenarios)
            """channel_scenario form: {CDL}-{A|B|C|D|E}-{delay_spread (ns)}-{speed (m/s)}
                                or {Umi|Uma}-{low|high}-[OnPL]-[OnSF]-{delay_spread (ns)}-{speed (m/s)}

                Ex: CDL-A-150-10"""

            chn_scn = channel_scenario.split('-')
            
            model = chn_scn[1]
            channel = chn_scn[0]
            enable_pl = True if 'OnPL' in chn_scn else False # Umi/Uma enable pathloss
            enable_sf = True if 'OnSF' in chn_scn else False # Umi/Uma enable shadow fading

            speed = float(chn_scn[-1])
            delay_spread = float(chn_scn[-2])
            

            if 'CDL' == channel:
                channel_model = CDL(model = model,
                                        delay_spread = delay_spread*1e-9,
                                        carrier_frequency = carrier_frequency,
                                        ut_array = ue_antenna,
                                        bs_array = gnb_array,
                                        direction = "uplink",
                                        min_speed = speed,
                                        max_speed = speed)

            else:
                if 'Umi' == channel:
                    channel_model = UMi(carrier_frequency = carrier_frequency,
                                        o2i_model = model,
                                        ut_array = ue_antenna,
                                        bs_array = gnb_array,
                                        direction = "uplink",
                                        enable_pathloss = enable_pl,
                                        enable_shadow_fading = enable_sf)
                elif 'Uma' == channel:
                    channel_model = UMa(carrier_frequency = carrier_frequency,
                                        o2i_model = model,
                                        ut_array = ue_antenna,
                                        bs_array = gnb_array,
                                        direction = "uplink",
                                        enable_pathloss = enable_pl,
                                        enable_shadow_fading = enable_sf)

            simulator = MySimulator(pusch_config)

            channel_i = OFDMChannel(channel_model=channel_model, resource_grid=simulator.resource_grid,
                                    add_awgn=False, normalize_channel=True, return_channel=True)
            
            for esno_db in esno_dbs:
                no_scaling = pow(10., -esno_db / 10.)
                if channel in ['Umi', 'Uma']:
                    channel_i._cir_sampler.set_topology(*gen_topology(1,1,channel.lower(),min_ut_velocity=speed, max_ut_velocity=speed))

                for n,slot in enumerate(slots):
                    status_str = f"(config {config_idx} | channel {channel_scenario} | {esno_db} dB | slot {slot} | Sample: {n+1}/{len_per_case}"
                    pbar.set_description(status_str)
                    simulator.pusch_config.carrier.slot_number = slot
                    simulator.update_pilots(Pusch_Pilots[slot])
                    # print(tf.math.reduce_sum(simulator.pusch_config.dmrs_grid, [0,1]))
                    
                    b, c, y= simulator.sim(1, channel_i, no_scaling, return_channel=False)
                    # print(tf.math.reduce_sum(x, [0,1,2,4]))
                    
                    # b_hat, c_soft, crc = simulator.rec(y)
                    # print(crc)

                    assert b.shape[0] == b.shape[1] == c.shape[0] == c.shape[1] == y.shape[0] == y.shape[1] == 1
                    b = tf.cast(b, dtype=tf.uint8)[0][0]
                    c = tf.cast(c, dtype=tf.uint8)[0][0]
                    r = tf.transpose(tf.constant(simulator.pusch_config.dmrs_grid, dtype=y.dtype), [0, 2, 1])
                    y =  y[0][0]

                    timestamp = datetime.now().strftime("%Y%m%d%H%M%S%f")


                    # print(y, r)
                    if save_dataset == 'hdf5':
                        save_hdf5([b,c,y,r], f'{hdf5_dir}/{name}', timestamp)
                    if save_dataset == 'pickle':
                        save_pickle([b,c,y,r], f'{pickle_dir}/{name}', timestamp)

                    
                    
                    pusch_records.append(PuschRecord(
                                        nPhyCellId=pusch_config.carrier.n_cell_id,
                                        nSFN=(n // len_pusch) % 1023,
                                        nSlot=slot,
                                        nPDU=1,
                                        nGroup=1,
                                        nUlsch=1,
                                        nUlcch=0,
                                        nRachPresent=0,
                                        nRNTI=pusch_config.n_rnti,
                                        nUEId=0,
                                        nBWPSize=pusch_config.n_size_bwp,
                                        nBWPStart=pusch_config.n_start_bwp,
                                        nSubcSpacing=pusch_config.carrier.mu,
                                        nCpType=pusch_config.My_Config.Sys.CpType,
                                        nULType=0,
                                        nMcsTable=pusch_config.tb.mcs_table - 1,
                                        nMCS=pusch_config.tb.mcs_index,
                                        nTransPrecode=pusch_config.My_Config.Ue[0].TransformPrecoding,
                                        nTransmissionScheme=pusch_config.My_Config.Ue[0].CodeBookBased,
                                        nNrOfLayers=pusch_config.num_layers,
                                        nPortIndex=pusch_config.dmrs.dmrs_port_set,
                                        nNid=pusch_config.tb.n_id,
                                        nSCID=pusch_config.dmrs.n_scid,
                                        nNIDnSCID=pusch_config.dmrs.n_id[0],
                                        nNrOfAntennaPorts=pusch_config.My_Config.Sys.NRxAnt,
                                        nVRBtoPRB=0,
                                        nPMI=pusch_config.My_Config.Ue[0].Tpmi,
                                        nStartSymbolIndex=pusch_config.symbol_allocation[0],
                                        nNrOfSymbols=pusch_config.symbol_allocation[1],
                                        nResourceAllocType=1,
                                        nDMRSTypeAPos=pusch_config.dmrs.type_a_position,
                                        nRBStart=pusch_config.first_resource_block,
                                        nRBSize=pusch_config.num_resource_blocks,
                                        nTBSize=(pusch_config.tb_size//8),
                                        nRV=pusch_config.My_Config.Sys.rvSeq,
                                        nHARQID=n % 16,
                                        nNDI=1,
                                        nMappingType=pusch_config.My_Config.Ue[0].PuschMappingType,
                                        nDMRSConfigType=pusch_config.My_Config.Ue[0].DmrsConfigurationType,
                                        nNrOfCDMs=pusch_config.dmrs.num_cdm_groups_without_data,
                                        nNrOfDMRSSymbols=pusch_config.dmrs.length,
                                        nDMRSAddPos=pusch_config.dmrs.additional_position,
                                        nPTRSPresent=pusch_config.My_Config.Ue[0].Ptrs,
                                        nAck=pusch_config.My_Config.Ue[0].OAck,
                                        nAlphaScaling=pusch_config.My_Config.Ue[0].ScalingFactor,
                                        nBetaOffsetACKIndex=pusch_config.My_Config.Ue[0].IHarqAckOffset,
                                        nCsiPart1=pusch_config.My_Config.Ue[0].OCsi1,
                                        nBetaOffsetCsiPart1Index=pusch_config.My_Config.Ue[0].ICsi1Offset,
                                        nCsiPart2=pusch_config.My_Config.Ue[0].OCsi2,
                                        nBetaOffsetCsiPart2Index=pusch_config.My_Config.Ue[0].ICsi2Offset,
                                        nTpPi2BPSK=pusch_config.My_Config.Ue[0].TpPi2Bpsk,
                                        nTPPuschID=pusch_config.My_Config.Ue[0].NRsId,
                                        nRxRUIdx=np.arange(0, pusch_config.My_Config.Sys.NRxAnt),
                                        nUE=1,
                                        nPduIdx=[0],
                                        Channel_model=f"{channel}-{model}",
                                        Speed=speed,
                                        Delay_spread=delay_spread,
                                        Esno_db=esno_db,
                                        Data_filename=timestamp,
                                        Data_dirname=name
                                    )
                                )
                    pbar.update(1)  # Increment progress

            df = pd.DataFrame.from_records(pusch_records, columns=PuschRecord._fields)
            if save_dataset: df.to_parquet(f'{parquet_dir}/{name}.parquet', engine="pyarrow")
    return df

In [38]:
assert False

AssertionError: 

# Case 4RB gen...

In [13]:
cfg_4 = MyConfig(SystemConfig(), [UeConfig()])
pusch_4 = MyPUSCHConfig(cfg_4)
pusch_4.show()

Carrier Configuration
cyclic_prefix : normal
cyclic_prefix_length : 2.3437500000000002e-06
frame_duration : 0.01
frame_number : 0
kappa : 64.0
mu : 1
n_cell_id : 246
n_size_grid : 273
n_start_grid : 0
num_slots_per_frame : 20
num_slots_per_subframe : 2
num_symbols_per_slot : 14
slot_number : 4
sub_frame_duration : 0.001
subcarrier_spacing : 30
t_c : 5.086263020833334e-10
t_s : 3.2552083333333335e-08

PUSCH Configuration
My_Config : MyConfig(Sys=SystemConfig(NCellId=246, FrequencyRange=1, BandWidth=100, Numerology=1, CpType=0, NTxAnt=1, NRxAnt=8, BwpNRb=273, BwpRbOffset=0, harqProcFlag=0, nHarqProc=1, rvSeq=0), Ue=[UeConfig(TransformPrecoding=0, Rnti=20002, nId=246, CodeBookBased=0, DmrsPortSetIdx=[0], NLayers=1, NumDmrsCdmGroupsWithoutData=2, Tpmi=0, FirstSymb=0, NPuschSymbAll=14, RaType=1, FirstPrb=31, NPrb=4, FrequencyHoppingMode=0, McsTable=0, Mcs=3, ILbrm=0, nScId=0, NnScIdId=246, DmrsConfigurationType=0, DmrsDuration=1, DmrsAdditionalPosition=1, PuschMappingType=0, DmrsTypeAPositi

In [14]:
pusch_4_2 = pusch_4.clone()
pusch_4_2.n_rnti = 20069
pusch_4_2.tb.n_id = 10
pusch_4_2.phy_cell_id = 123
pusch_4_2.show()

Carrier Configuration
cyclic_prefix : normal
cyclic_prefix_length : 2.3437500000000002e-06
frame_duration : 0.01
frame_number : 0
kappa : 64.0
mu : 1
n_cell_id : 123
n_size_grid : 273
n_start_grid : 0
num_slots_per_frame : 20
num_slots_per_subframe : 2
num_symbols_per_slot : 14
slot_number : 4
sub_frame_duration : 0.001
subcarrier_spacing : 30
t_c : 5.086263020833334e-10
t_s : 3.2552083333333335e-08

PUSCH Configuration
My_Config : MyConfig(Sys=SystemConfig(NCellId=246, FrequencyRange=1, BandWidth=100, Numerology=1, CpType=0, NTxAnt=1, NRxAnt=8, BwpNRb=273, BwpRbOffset=0, harqProcFlag=0, nHarqProc=1, rvSeq=0), Ue=[UeConfig(TransformPrecoding=0, Rnti=20002, nId=246, CodeBookBased=0, DmrsPortSetIdx=[0], NLayers=1, NumDmrsCdmGroupsWithoutData=2, Tpmi=0, FirstSymb=0, NPuschSymbAll=14, RaType=1, FirstPrb=31, NPrb=4, FrequencyHoppingMode=0, McsTable=0, Mcs=3, ILbrm=0, nScId=0, NnScIdId=246, DmrsConfigurationType=0, DmrsDuration=1, DmrsAdditionalPosition=1, PuschMappingType=0, DmrsTypeAPositi

In [15]:
# data_dir = '/content/dataset' # if colab
data_dir = '../Pusch_data/dataset' # if workspace

pusch_4_2 = pusch_4.clone()
pusch_4_2.n_rnti = 20069
pusch_4_2.My_Config.Ue[0].FirstPrb = 213
pusch_4_3 = pusch_4.clone()
pusch_4_3.n_rnti = 11235
pusch_4_3.My_Config.Ue[0].FirstPrb = 100
name = datetime.now().strftime("%Y%m%d%H%M%S%f")

start = time.time()
df = generate_data(name=f'{name}',
              data_dir=data_dir,
              pusch_configs=[
                  pusch_4,
                  # pusch_4_2,
                  # pusch_4_3
                  ],
              channel_scenarios=[
                  'CDL-A-150-1',
                  'CDL-B-150-1',
                  'CDL-C-150-1',
                  'CDL-D-150-1',
                  'CDL-E-150-1',
                  'CDL-A-10-10',
                  'CDL-B-10-10',
                  'CDL-C-10-10',
                  'CDL-D-10-10',
                  'CDL-E-10-10',
                  'CDL-A-50-4',
                  'CDL-B-50-4',
                  'CDL-C-50-4',
                  'CDL-D-50-4',
                  'CDL-E-50-4'
                  ],
              esno_dbs=[i for i in np.arange(5.,5.1,0.5)],
              slots=[4,5,14,15]*3,
              save_dataset=None
)
duration = time.time() - start

(config 0 | channel CDL-A-150-1 | 5.0 dB | slot 5 | Sample: 6/12:   3%|▎         | 5/180 [00:05<03:15,  1.12s/it] 


KeyboardInterrupt: 

In [ ]:
# !cp /content/dataset/parquet/{name}.parquet /content/drive/MyDrive/Pusch_data/dataset/parquet
# !cp /content/dataset/hdf5/{name}.hdf5 /content/drive/MyDrive/Pusch_data/dataset/hdf5

# Case 273 RB gen...

In [22]:
ue_273 = UeConfig(
                TransformPrecoding = 0,
                Rnti = 40007,
                nId = 443,
                CodeBookBased = 0,
                DmrsPortSetIdx = [0],
                NLayers = 1,
                NumDmrsCdmGroupsWithoutData = 2,
                Tpmi = 0,
                FirstSymb = 0,
                NPuschSymbAll = 14,
                RaType = 1,
                FirstPrb = 0,
                NPrb = 273,
                FrequencyHoppingMode = 0,
                McsTable = 0,
                Mcs = 3,
                ILbrm = 0,
                nScId = 0,
                NnScIdId = 443,
                DmrsConfigurationType = 0,
                DmrsDuration = 1,
                DmrsAdditionalPosition = 1,
                PuschMappingType = 0,
                DmrsTypeAPosition = 3,
                HoppingMode = 0,
                NRsId = 0,
                Ptrs = 0,
                ScalingFactor = 0,
                OAck = 0,
                IHarqAckOffset = 11,
                OCsi1 = 0,
                ICsi1Offset = 7,
                OCsi2 = 0,
                ICsi2Offset = 0,
                NPrbOh = 0,
                nCw = 1,
                TpPi2Bpsk = 0
            )
cfg_273 = MyConfig(
                SystemConfig(
                    NCellId = 443,
                    FrequencyRange = 1,
                    BandWidth = 100,
                    Numerology = 1,
                    CpType = 0,
                    NTxAnt = 1,
                    NRxAnt = 8,
                    BwpNRb = 273,
                    BwpRbOffset = 0,
                    harqProcFlag = 0,
                    nHarqProc = 1,
                    rvSeq = 0
                ),
                [ue_273] 
            )
pusch_273 = MyPUSCHConfig(cfg_273)
pusch_273.show()

Carrier Configuration
cyclic_prefix : normal
cyclic_prefix_length : 2.3437500000000002e-06
frame_duration : 0.01
frame_number : 0
kappa : 64.0
mu : 1
n_cell_id : 443
n_size_grid : 273
n_start_grid : 0
num_slots_per_frame : 20
num_slots_per_subframe : 2
num_symbols_per_slot : 14
slot_number : 4
sub_frame_duration : 0.001
subcarrier_spacing : 30
t_c : 5.086263020833334e-10
t_s : 3.2552083333333335e-08

PUSCH Configuration
My_Config : MyConfig(Sys=SystemConfig(NCellId=443, FrequencyRange=1, BandWidth=100, Numerology=1, CpType=0, NTxAnt=1, NRxAnt=8, BwpNRb=273, BwpRbOffset=0, harqProcFlag=0, nHarqProc=1, rvSeq=0), Ue=[UeConfig(TransformPrecoding=0, Rnti=40007, nId=443, CodeBookBased=0, DmrsPortSetIdx=[0], NLayers=1, NumDmrsCdmGroupsWithoutData=2, Tpmi=0, FirstSymb=0, NPuschSymbAll=14, RaType=1, FirstPrb=0, NPrb=273, FrequencyHoppingMode=0, McsTable=0, Mcs=3, ILbrm=0, nScId=0, NnScIdId=443, DmrsConfigurationType=0, DmrsDuration=1, DmrsAdditionalPosition=1, PuschMappingType=0, DmrsTypeAPosit

In [23]:
# Set a random seed for reproducibility
random.seed(42)
# Generate 200 unique PCI values (0-1023)
pci_values = random.sample(range(1024), 40)

# Generate 200 random RNTI values (0-65535)
rnti_values = [random.randint(0, 65535) for _ in range(40)]

In [24]:
pusch_config_273RB = []
for pci, rnti in zip(pci_values, rnti_values):
    pusch_instance = pusch_273.clone()
    pusch_instance.phy_cell_id = pci
    pusch_instance.n_rnti = rnti
    pusch_config_273RB.append(pusch_instance)

In [25]:
# data_dir = '/content/dataset' # if colab
data_dir = '../Pusch_data/dataset' # if workspace
name = datetime.now().strftime("%Y%m%d%H%M%S%f")
start = time.time()
df = generate_data(name=f'{name}',
              data_dir=data_dir,
              pusch_configs=[pusch_273],
              channel_scenarios=[
                  'CDL-A-150-1',
                  'CDL-B-150-1',
                  'CDL-C-150-1',
                  'CDL-D-150-1',
                  'CDL-E-150-1',
                  'CDL-A-10-10',
                  'CDL-B-10-10',
                  'CDL-C-10-10',
                  'CDL-D-10-10',
                  'CDL-E-10-10',
                  'CDL-A-50-4',
                  'CDL-B-50-4',
                  'CDL-C-50-4',
                  'CDL-D-50-4',
                  'CDL-E-50-4'
                  ],
              esno_dbs=[i for i in np.arange(5.,-5.1,-0.5)],
              slots=[
                  4,
                  5,
                  14,
                  15
                  ]*41,
              save_dataset=None
)
duration = time.time() - start

(config 0 | channel CDL-E-150-1 | 5.0 dB | slot 5 | Sample: 2/164:   0%|          | 1/3444 [00:09<9:03:32,  9.47s/it]

tf.Tensor(
[[[ 9.0296823e-01+8.72570455e-01j -4.8863450e-01-6.89292729e-01j
    7.8497422e-01-9.72536385e-01j ... -1.4999557e-01+1.17953289e+00j
   -2.5447989e-01+9.98702049e-01j  1.3749704e+00+2.07332224e-01j]
  [-1.0205951e+00+7.54897654e-01j  5.1861048e-01-9.49026525e-01j
   -8.3181012e-01-5.19862652e-01j ... -1.0331440e+00-3.49052548e-02j
    4.3161511e-01-2.93306291e-01j  1.0264136e+00+4.09982145e-01j]
  [ 1.0501184e+00-3.85237515e-01j -8.1126738e-01+7.32223272e-01j
    6.4059949e-01+1.17278576e+00j ... -9.9097115e-01-1.18148506e-01j
    8.7369150e-01-7.55072951e-01j  1.3126286e+00+1.37472361e-01j]
  ...
  [-1.0059856e+00+1.26378012e+00j -3.5430333e-01-1.84470266e-01j
    1.1177832e+00-1.34646416e+00j ...  1.0033268e+00-4.70802456e-01j
    1.3889062e+00-1.40495837e+00j -2.1580805e-01-1.31870613e-01j]
  [ 8.2570338e-01+6.47168517e-01j  6.2989151e-01+1.63372397e+00j
   -5.5115426e-01+3.61644804e-01j ... -1.0574713e+00+1.74862731e+00j
    9.7353673e-01-1.43676519e+00j  3.4607849e-01+

(config 0 | channel CDL-E-150-1 | 5.0 dB | slot 14 | Sample: 3/164:   0%|          | 2/3444 [00:10<4:07:55,  4.32s/it]

tf.Tensor(
[[[ 1.0613214 -1.3829567j  -1.1013778 -0.92952335j
   -1.0112197 -1.2541771j  ... -0.25512928+0.42410764j
    1.1686139 +0.6099378j  -0.50144905-1.2538223j ]
  [ 0.8784045 -0.16933542j  0.35420495+0.13422585j
   -1.0893286 -0.69903606j ...  0.03467178+0.713329j
   -0.680764  -0.8123609j   0.7620687 -0.553295j  ]
  [ 1.4287024 +1.1251765j   0.49754474-0.01594985j
   -1.0869275 -0.9747029j  ...  0.39575306+0.0185042j
   -0.5860789 +0.8710575j  -1.3825216 -0.85332763j]
  ...
  [-1.1805382 -0.906949j   -0.1672032 -0.39590296j
    0.8587944 +0.99449277j ... -1.0293492 +0.06408655j
    1.0502787 +1.5088769j  -0.5670751 -0.11827411j]
  [ 0.94565135+0.86821926j  0.30146962+1.4389318j
   -0.8425403 -0.36711517j ...  0.20607114+0.83637786j
    0.9078161 +0.38928175j -1.364419  -0.48894933j]
  [-0.5041704 -0.54363656j  0.6099759 -0.7621819j
   -1.0724579 +0.31109148j ...  0.7455448 -1.0694313j
    0.695223  +1.0099438j  -0.82966053-0.0081386j ]]

 [[ 1.4456214 -0.87985766j -1.0087464 -

(config 0 | channel CDL-E-150-1 | 5.0 dB | slot 15 | Sample: 4/164:   0%|          | 3/3444 [00:10<2:32:38,  2.66s/it]

tf.Tensor(
[[[-8.5827404e-01+1.3782555j  -7.3219383e-01-1.5662181j
   -3.1403196e-01-0.16238493j ... -3.3150727e-01-0.53999525j
    2.7702469e-01+1.0951784j   3.9343756e-01+0.537788j  ]
  [ 9.5709085e-01-0.38706052j -1.0012314e+00+1.1508539j
    3.1732175e-01-1.182718j   ... -4.0747553e-01+1.3389843j
   -5.0833046e-01-0.45184985j  2.9530177e-01-1.4921896j ]
  [-1.0850453e+00-0.69056696j  5.9143841e-01-1.7782166j
    4.4890034e-01+1.2458612j  ... -1.0640392e+00-0.1683813j
    1.0807693e-01+0.46324092j -1.4447212e-02+0.48769984j]
  ...
  [-1.2903733e+00-1.4025855j   2.6457000e-01+0.39606306j
    1.3270835e+00+1.3412293j  ... -5.1473576e-01+0.3452862j
   -6.2963784e-01+0.92423207j -1.8631695e-01-0.7023711j ]
  [-6.4083970e-01+0.89613324j  7.8194404e-01-0.76457494j
    4.0239224e-01+0.9632432j  ... -7.5032496e-01-0.9135183j
   -5.1519006e-01-0.04266936j  3.5471991e-01+1.450663j  ]
  [-1.0919731e+00+0.37747496j -2.9128408e-01-0.63508123j
    7.4096936e-01-1.083761j   ...  3.4662041e-01-0.96

(config 0 | channel CDL-E-150-1 | 5.0 dB | slot 4 | Sample: 5/164:   0%|          | 4/3444 [00:11<1:50:02,  1.92s/it] 

tf.Tensor(
[[[ 0.9111103 +3.79285365e-01j -0.9238392 +7.49282539e-01j
   -0.935701  -4.73314196e-01j ...  0.15130943+5.93528152e-01j
   -0.562668  -2.95812964e-01j  0.9315451 -5.54507017e-01j]
  [-0.47793213-5.19148827e-01j -0.08285177-1.13038886e+00j
    1.3600936 +8.02508354e-01j ...  1.1447372 +2.03613490e-01j
   -0.6238796 -1.07203734e+00j  1.6701318 +1.59683609e+00j]
  [-0.82228947+7.89435923e-01j -0.98322785-7.90364265e-01j
   -0.89564824-3.34625214e-01j ...  0.21667069-9.41886425e-01j
    0.9223012 +1.13388479e-01j  1.1152923 -1.66178870e+00j]
  ...
  [-0.88722366+8.73475492e-01j -0.26954657-4.08273824e-02j
    0.65835994+6.63929522e-01j ... -0.42377073+3.24906617e-01j
    0.998791  -1.77426815e+00j  0.81977737-3.22117424e-03j]
  [-0.13481182-1.05127883e+00j -0.8447558 -7.55575120e-01j
    0.72870207-7.23820806e-01j ...  0.8478415 +8.74763429e-01j
   -0.4934426 +4.39473331e-01j -0.85163605-5.69117427e-01j]
  [-1.0528902 -9.24430847e-01j -0.39114925+8.19731474e-01j
    1.0209992 

(config 0 | channel CDL-E-150-1 | 5.0 dB | slot 5 | Sample: 6/164:   0%|          | 5/3444 [00:12<1:24:45,  1.48s/it]

tf.Tensor(
[[[-0.21643177+0.73074067j -0.5135477 +0.14823973j
    0.02377862+0.5940726j  ...  1.1991181 -0.6979279j
   -1.1065377 +0.7433481j   0.7307382 +1.2628846j ]
  [ 0.32521188-0.8078877j   0.88979506-1.637836j
   -0.93321717-0.13662547j ...  0.40391162-0.9798348j
    0.6461898 -0.4004469j  -0.26686898-0.7308431j ]
  [ 1.6376619 -0.8739702j   0.3119928 +0.92991835j
   -0.6108782 +0.21067935j ...  0.45942426-0.07094878j
    0.71169853+0.61173826j  0.83287567+1.2438061j ]
  ...
  [-0.67373085+1.2102364j   0.24093887-0.559494j
    0.37199047-1.1567655j  ... -0.24520831+0.00836083j
    1.2835968 -0.41617364j  0.3222336 +0.9016033j ]
  [-1.1352473 +0.7696261j   0.5711821 -0.79611784j
    0.6178473 +0.6823231j  ... -1.221915  +0.48936045j
    0.7368841 +0.5438458j  -0.5052479 +0.37832147j]
  [-1.2853405 -0.95741045j -0.9445772 -0.2401169j
   -1.0319971 +0.17256323j ...  0.58445096-0.23656473j
   -0.87229127-0.45418447j  1.2532364 +0.59021276j]]

 [[ 0.46669173+1.3701634j  -0.86762536+0

(config 0 | channel CDL-E-150-1 | 5.0 dB | slot 14 | Sample: 7/164:   0%|          | 6/3444 [00:13<1:10:40,  1.23s/it]

tf.Tensor(
[[[ 0.9906269 +0.93771935j -1.1452379 -1.038054j
   -0.4080045 +0.2876461j  ... -1.0939972 -0.11119837j
    0.95870966+0.00305325j  1.0091963 -1.4353125j ]
  [ 0.19911528-0.83230406j  0.94544137+0.5863556j
   -0.89617735-0.6770205j  ...  0.6524814 +0.4438355j
   -1.0814307 -0.40382993j -1.3991296 -0.21463436j]
  [ 1.0453625 +0.97257084j -0.45041424-0.27231047j
    0.3212236 -1.7703433j  ... -0.60521924+0.7616599j
    0.37010783-0.5925494j  -1.110128  -0.8352502j ]
  ...
  [-0.10518044-1.0439938j   0.47226173+0.1781123j
    0.98739624+0.976703j   ... -0.9232825 +0.47074258j
    1.5378022 +1.6887504j  -0.16463512-0.54908895j]
  [ 0.4367338 +0.4665165j  -0.720418  -1.072147j
    0.3439616 -0.306426j   ...  1.040184  -1.0090677j
   -1.7040594 +0.14769119j -0.34349287+0.8898182j ]
  [ 0.8472357 -0.14043832j -0.11574024+0.8211161j
   -0.3735757 -1.193404j   ...  0.50839555-0.35356823j
   -1.6895661 +0.23834735j  0.6379664 -0.23907j   ]]

 [[ 0.68858624+1.1497227j  -0.16126361-0.41

(config 0 | channel CDL-E-150-1 | 5.0 dB | slot 15 | Sample: 8/164:   0%|          | 7/3444 [00:13<1:00:49,  1.06s/it]

tf.Tensor(
[[[-0.36809424+0.5354738j  -0.5632485 +0.7954773j
   -0.41758746-0.8271122j  ...  0.5097884 +0.96617436j
   -0.2890013 -0.6279143j   0.4480292 -0.22007865j]
  [-0.46434754-0.65664077j -0.35384098-0.27470586j
   -0.07830268-0.88334143j ... -0.5398435 +0.8063432j
   -0.6496258 -0.64178956j  0.03143239+1.0739747j ]
  [ 0.17023551-0.65655905j  0.93653   -0.6999503j
   -0.4523125 -0.5689517j  ...  0.9686674 -0.86564475j
   -0.97348166+0.22038603j -1.0635536 -0.39680457j]
  ...
  [-1.2170529 -1.0545304j   0.03937587+0.45706955j
    0.77907574+0.97832227j ...  0.23170254-0.27693012j
   -1.8189745 +1.3361566j   0.37787247+0.5315442j ]
  [ 0.26595697-0.5765357j   0.2415519 +0.64337796j
    0.24003619-0.70590496j ... -1.0570682 -0.54201204j
    1.0117218 -0.9792291j  -0.27019933-0.7171763j ]
  [-1.0149834 -0.6377686j  -0.24739674-0.9015931j
   -0.3864407 -0.7367292j  ...  0.8198358 +1.5757668j
    0.5126746 +0.29574248j -0.47335708-1.2733628j ]]

 [[-1.0757699 +0.76344526j -1.0911678 

(config 0 | channel CDL-E-150-1 | 5.0 dB | slot 4 | Sample: 9/164:   0%|          | 8/3444 [00:14<54:32,  1.05it/s]   

tf.Tensor(
[[[ 0.99303705-0.9010143j  -0.35425648-0.9051892j
   -1.1642109 +0.42065686j ...  0.40655455-0.54038244j
    0.3780888 +0.89614886j -0.6970272 -1.0250204j ]
  [ 0.78746223+0.78459865j -1.1851853 +0.6267383j
    1.7504537 -0.46265385j ...  0.7400381 +0.58650875j
    0.48825353-0.95413756j -0.79286337+0.14224556j]
  [-0.2464047 +1.0228348j   0.24902785-0.6094379j
   -0.859737  +0.36744496j ... -0.00395271+0.20515126j
   -0.10714203-0.77218634j  0.80722487-1.7445025j ]
  ...
  [-1.2552835 +1.2399299j   0.32277668-0.08294916j
    1.0891128 +1.4062614j  ...  0.2746853 +0.04002161j
    0.11754066-1.5321527j   0.3903744 -0.24538809j]
  [-1.2192996 +0.48606402j -0.93218386-0.36472917j
    0.77192205-1.0090957j  ...  0.6003585 -1.1313713j
    0.33371028-1.3122578j   0.04776007-0.6841358j ]
  [-1.224055  -0.07045841j -0.6596422 -0.7738939j
    0.11716211+1.1254706j  ...  1.0753417 +0.51984584j
    0.14775369-0.75606394j -0.605257  -0.5979786j ]]

 [[ 1.1751523 -0.2788557j  -0.4003901 

(config 0 | channel CDL-E-150-1 | 5.0 dB | slot 5 | Sample: 10/164:   0%|          | 9/3444 [00:15<49:43,  1.15it/s]

tf.Tensor(
[[[-0.6616944 -1.4144197j   0.74717844+1.0470622j
   -0.99107945-0.75716764j ...  0.36714092-0.8545861j
   -1.4445877 +0.8283901j   0.62456703+0.47608835j]
  [ 0.4698282 -0.41171584j  0.8893671 +0.8332593j
   -0.5043926 +0.8544533j  ... -0.7424021 +1.0820636j
    1.0238726 -1.6177489j  -0.53928083-0.4091351j ]
  [ 0.4849987 +0.6693467j   0.6404307 -0.923995j
   -0.6950295 -0.2592703j  ... -0.46747285+0.38263935j
    0.44101036+1.3787014j   1.4009135 +1.2431538j ]
  ...
  [-1.7073853 +1.5726627j  -0.65151376-0.36523235j
    1.1150208 -0.42000675j ...  0.12943265+0.11165213j
    0.83318514-1.6781912j  -0.00983263+0.24052203j]
  [ 0.80729294+1.0893972j   1.108988  -0.9475523j
   -0.4286263 -0.61504686j ...  0.52350813-1.1550696j
    0.23755005-1.2723575j   0.97647035-0.91452086j]
  [ 0.99184835+1.8993275j   1.3910491 -0.58342195j
    0.30889028-1.5235665j  ...  0.13736999-1.1872998j
    0.36470696-0.42412055j  0.8340235 -1.6469231j ]]

 [[-0.52798057-0.44940966j  0.39026883+1.2

(config 0 | channel CDL-E-150-1 | 5.0 dB | slot 14 | Sample: 11/164:   0%|          | 10/3444 [00:15<46:59,  1.22it/s]

tf.Tensor(
[[[-1.2437325 +1.3047874j  -1.2517657 +0.30547485j
   -0.5913697 -1.3894618j  ... -0.43020663-0.64240384j
   -0.35951263+0.6989744j  -0.8226123 +0.06470358j]
  [-0.8922257 +0.65921396j -0.2707638 +0.74247175j
    0.7335887 +1.1052194j  ...  0.11245281-0.22095752j
   -1.174526  +0.20849913j -0.6323169 -0.26524037j]
  [-1.329829  +0.8410878j   0.92072177-0.76219285j
   -0.61596364-0.44294184j ...  0.41800883+1.2751427j
   -0.27351317-0.40721107j  1.2893956 -0.49539775j]
  ...
  [-0.698321  -1.5995897j   0.31826043+0.44474572j
    1.2614517 +0.7685207j  ...  0.10394578+0.53963655j
    1.6324024 +0.31280255j -0.48219836+0.11785916j]
  [ 0.36038032+0.73471624j -0.89451474-0.71317184j
    1.8287053 -0.9493901j  ...  0.2738452 +0.19190043j
   -0.14369059+0.90416455j  1.0803957 +0.662701j  ]
  [ 1.125345  -0.5951039j   0.7629418 -0.13131529j
    0.57550246-0.8723302j  ... -0.8886865 -0.36398035j
    0.94397914+0.5803618j  -0.852316  +0.93869716j]]

 [[-0.2696529 +0.04899526j -0.5069

(config 0 | channel CDL-E-150-1 | 5.0 dB | slot 15 | Sample: 12/164:   0%|          | 11/3444 [00:16<45:39,  1.25it/s]

tf.Tensor(
[[[-0.24645555-0.8292579j  -0.17475629+1.4593043j
    0.94652903+0.96898115j ...  0.91682804+1.0302076j
   -0.7549964 +0.1946274j  -0.18416575-0.73754317j]
  [ 0.6130094 -0.8851408j   0.37364382-0.6527331j
   -1.5762367 -0.6112978j  ... -0.7238696 -0.8787185j
    0.84977084+1.0554668j  -0.95474195-0.8213228j ]
  [-0.84931165+0.8135247j  -0.06958508-0.5988166j
    1.0023056 +0.77672386j ...  0.4890689 -0.22245929j
    0.56583726-0.14155862j -0.7281197 -1.2146273j ]
  ...
  [-1.3195555 -1.2347044j  -0.74504155-0.6736599j
    1.1142085 +1.5440664j  ... -0.31412345+0.04587778j
   -0.49518073+1.0629492j  -0.35992435-0.2521101j ]
  [ 0.81287354+1.1405983j  -1.3333609 -1.1961546j
    0.5480754 -0.7505281j  ...  0.21572539+1.0927583j
    0.73525727-0.43457365j -0.15226442+0.7391214j ]
  [-0.571549  -0.8846985j  -0.42521912+0.90918005j
   -0.30656666+1.677151j   ... -0.4793685 -1.3330578j
    0.7685191 -0.40216434j -0.29882437+0.8107677j ]]

 [[-0.3187116 -1.7732484j  -1.0312349 +1.4

(config 0 | channel CDL-E-150-1 | 5.0 dB | slot 4 | Sample: 13/164:   0%|          | 12/3444 [00:17<43:47,  1.31it/s] 

tf.Tensor(
[[[ 0.5497359 -0.6755658j  -1.2916379 -1.1269965j
   -0.250282  -1.3457309j  ... -0.54789907-0.83642966j
    1.3518295 +0.8121586j   0.81959796-0.12862134j]
  [-1.421413  +0.8635929j   1.2352042 +1.1576535j
   -0.25272006-1.3856798j  ...  0.74419785-0.22852927j
   -0.7184446 +1.2681594j   0.9433808 -0.45159543j]
  [ 0.40077832+1.6303883j  -0.4582754 -1.3846496j
    0.984901  -0.30620795j ... -0.44718906-0.5391125j
    0.9228935 +0.8314094j  -0.32413393-0.24105918j]
  ...
  [-1.457851  +2.1307335j  -0.5430535 +0.49491888j
    0.9346964 +0.939252j   ...  0.7660699 -0.5543148j
    1.2716947 -1.0281982j  -0.5872104 +0.04808924j]
  [-0.17713499-1.3395172j   0.23801756-1.2963567j
   -0.8497459 -1.0789839j  ... -0.82969993-0.28037566j
   -0.7393797 -0.6555799j  -1.2642214 -0.6196635j ]
  [-0.60277283+0.87951416j -0.65112305-0.7381613j
   -0.16255367+1.6363841j  ...  1.3784664 +0.88336396j
    0.95864254+0.47705838j  0.9308471 -1.2480836j ]]

 [[ 1.1626422 -0.8920486j  -1.6926348 -1

(config 0 | channel CDL-E-150-1 | 5.0 dB | slot 5 | Sample: 14/164:   0%|          | 13/3444 [00:18<43:40,  1.31it/s]

tf.Tensor(
[[[ 0.4457324 +0.6431529j   0.46134025-0.61818004j
   -1.1433859 -0.04789841j ... -0.8673717 +1.3838607j
   -1.3445871 +0.6380912j  -0.93571365+0.86585337j]
  [ 0.30495772-0.28089023j  1.5435339 -0.46615255j
   -0.18471032-1.3993288j  ... -0.8981972 +0.11469817j
    0.3349181 +1.4222864j   0.8391087 +0.86189437j]
  [-0.37640825-0.6940702j  -0.6689367 -0.87054354j
   -0.24765074-0.7395329j  ...  0.81464523-0.7634307j
    0.34612182+0.5997119j   0.92279893+1.2114238j ]
  ...
  [-1.1796318 +0.87603486j -0.10333656+0.25441813j
    1.7780082 -0.18266714j ... -0.6813684 +0.6100463j
    1.1514796 -1.3115792j  -0.24961391+0.44273052j]
  [ 1.3830545 +0.22720268j  1.3430613 +0.837327j
   -1.3187227 +0.81348413j ...  0.78185874+1.1705507j
   -0.7799668 -1.2125753j   0.2600286 +1.0190064j ]
  [ 0.89493096+0.9938561j   1.1719451 -0.67216814j
   -0.80304486+0.53921705j ... -0.9612082 +0.4895535j
    0.57559794+0.7262347j  -0.8087241 -0.51818544j]]

 [[ 0.7617166 +0.7256241j   1.0261213 -0

(config 0 | channel CDL-E-150-1 | 5.0 dB | slot 14 | Sample: 15/164:   0%|          | 14/3444 [00:18<45:18,  1.26it/s]

tf.Tensor(
[[[ 0.676159  +7.5645089e-02j -0.8782714 -7.2705734e-01j
   -1.3359631 +9.8534644e-02j ... -0.44029042-8.0369920e-01j
   -0.17659846+1.3106253e+00j  0.04258668+7.7484214e-01j]
  [-0.35953903-1.3320154e-01j  0.35452044-1.1134517e+00j
   -0.45812815-2.5516447e-01j ...  0.86468947+1.7595866e-01j
    1.3297763 -9.2311144e-01j  2.104165  +4.9157327e-01j]
  [-1.0569199 +1.3824761e+00j -1.2258427 +8.6850786e-01j
    0.5062976 +7.9844058e-02j ... -0.15566948+2.6071241e-01j
    0.36329645-1.1688566e-01j  1.115252  +6.2986785e-01j]
  ...
  [-0.94607496-7.4249303e-01j -0.548423  -2.2302936e-01j
    1.0144075 +1.3779140e+00j ...  0.646032  +3.7951154e-01j
    0.8871624 +3.9022055e-01j -0.33037   +2.2997886e-02j]
  [-0.49896476+5.8002698e-01j  0.20648074+8.3047396e-01j
    0.3631158 -1.2616159e+00j ...  1.325387  +1.0234555e+00j
    0.24945867+3.5427770e-01j -0.15386069-3.0442089e-01j]
  [-0.3459351 -1.4329202e+00j  0.16427547+7.6990932e-01j
   -0.8339087 -6.1260575e-01j ... -0.8691658 +

(config 0 | channel CDL-E-150-1 | 5.0 dB | slot 15 | Sample: 16/164:   0%|          | 15/3444 [00:19<45:12,  1.26it/s]

tf.Tensor(
[[[ 0.07211664-8.0303317e-01j  0.5505976 -1.2671939e+00j
    0.28218347+5.5074298e-01j ...  0.33324343+7.8788036e-01j
    0.68973684-1.1791046e+00j  0.7547037 -7.6624840e-01j]
  [-0.47969115+7.8227133e-01j  0.2590677 -5.3914112e-01j
   -0.6211665 +6.7744249e-01j ...  0.00611907+9.3080902e-01j
   -0.345543  -9.3903738e-01j  0.7677982 +1.0524004e+00j]
  [-0.65779614-1.1406314e+00j -1.1184111 +1.0950333e-01j
   -0.8783897 +1.1554278e+00j ...  1.4918894 -1.0654079e+00j
    0.28942087-5.8491814e-01j -0.26004744-6.4721739e-01j]
  ...
  [-1.5536808 -8.0478078e-01j  0.807809  -3.7632364e-01j
    0.5145358 +1.0967801e+00j ... -0.09068404+1.3859546e-01j
   -1.3545644 +1.6715686e+00j  0.06638532+8.4732883e-02j]
  [ 0.48691574+3.8827142e-01j -0.79091024+6.7289817e-01j
    0.79578394-4.1295087e-01j ...  0.93701357+9.1983259e-01j
    0.10291946+2.5512674e-01j -0.7985396 -1.0830157e+00j]
  [ 1.3769057 +9.8531097e-02j  1.1071568 -9.2510247e-01j
   -0.51304466-6.5353376e-01j ...  1.4898628 +

(config 0 | channel CDL-E-150-1 | 5.0 dB | slot 4 | Sample: 17/164:   0%|          | 16/3444 [00:20<43:41,  1.31it/s] 

tf.Tensor(
[[[-0.05765849+0.53267485j -0.60438466+0.36849457j
   -0.3125704 -1.1133963j  ...  0.31728202+0.7222965j
   -0.8824935 -0.7928222j   0.04913437+0.6318311j ]
  [ 0.6521461 +1.1034918j   0.62770027+0.42151934j
    1.2580678 +0.01658398j ...  0.7710985 -0.725706j
    0.30088764+0.35531795j  1.3726177 -1.4243441j ]
  [-0.00771809+0.67011166j -0.25887632-0.87161165j
   -0.5710056 +0.6257448j  ... -0.42928952+1.1281946j
   -0.45623526+0.9559355j  -0.85104275-1.1004392j ]
  ...
  [-0.4657238 +1.12107j    -0.11557795-0.54195935j
    0.34867886+1.6649557j  ... -0.14138007-0.11685927j
    1.4381237 -1.517684j   -0.8208319 +0.26153836j]
  [ 0.91978157+0.97831327j -0.97717416+1.3959802j
   -1.5267273 -0.2686618j  ...  0.67920876-0.62417793j
   -1.0998055 +0.9113215j   1.1155019 -0.5988038j ]
  [ 1.7206546 -0.22594604j -0.8835397 +0.6119932j
    0.6473547 +0.9740305j  ...  0.6837258 +0.5215994j
   -0.12780106+0.35429472j  0.9661702 +0.7804699j ]]

 [[-0.5866321 +0.5112607j  -0.46264544+0

(config 0 | channel CDL-E-150-1 | 5.0 dB | slot 5 | Sample: 18/164:   0%|          | 17/3444 [00:21<42:21,  1.35it/s]

tf.Tensor(
[[[-0.17181545-1.6104306j   0.03939623+1.1989152j
   -0.8743899 +1.3336188j  ...  0.21115848-0.9516976j
    1.1198702 -1.2214551j  -1.1558988 +0.6198798j ]
  [-0.29071468+1.0869803j  -0.78943896+0.9682776j
   -0.79373133-0.77222323j ... -0.46131027+0.12559736j
   -0.3485187 -1.8317897j  -0.7204754 -1.3633945j ]
  [-0.98679835+0.5830821j   1.089881  +0.7204334j
    1.3235791 -0.63573587j ... -0.8598273 +0.12458885j
   -0.8469985 -0.7242331j  -1.4298555 -1.0610728j ]
  ...
  [-1.6795089 +0.70344424j  0.55859005+0.04508256j
    1.0293941 -0.85136664j ...  0.35816646+0.19925414j
    1.5608476 -1.1813576j  -0.48273575-0.28262356j]
  [ 0.32251954-1.3202491j   0.992581  -0.7836568j
   -0.4970049 -0.6212446j  ... -1.0948915 +0.9104516j
    0.37896654+1.0774875j  -0.47822234+0.0268082j ]
  [ 0.72351474-1.5442035j  -0.7654931 +0.8118347j
   -0.9410435 +0.22187161j ...  1.62451   +0.46724808j
    0.5590338 -1.0454481j   1.3762383 +0.4301435j ]]

 [[-0.7955098 -0.48716804j -1.0591325 +0

(config 0 | channel CDL-E-150-1 | 5.0 dB | slot 14 | Sample: 19/164:   1%|          | 18/3444 [00:21<41:55,  1.36it/s]

tf.Tensor(
[[[-0.69357437-0.5961234j  -1.4605081 +0.2972397j
    0.7148893 -1.1677526j  ...  1.2913125 +1.0260333j
   -1.1565368 +0.03329259j -0.43824914+0.41915575j]
  [ 1.2969408 -1.4165957j  -0.61248875+0.528063j
   -0.39320362+0.49040443j ...  0.40586993+1.0994078j
   -0.9148292 -1.7289383j   0.52466774+1.0747675j ]
  [-0.00287497+0.8172554j  -0.12078249+0.602447j
   -0.9233946 +0.980877j   ...  0.6168153 -1.2693719j
   -1.2051744 +0.68869907j  0.7885863 +1.1446162j ]
  ...
  [-1.5872743 -1.1092145j   0.31193796+0.78029627j
    0.91277915+1.7052009j  ... -0.5782971 +0.33065578j
    1.5587169 +1.1341131j  -0.60783166+0.22131476j]
  [ 0.5081568 +0.27103108j -0.6829462 -1.47768j
    0.20623794+0.92401946j ... -0.85138565+1.1365056j
    1.186346  -1.266279j    1.3034127 -0.7782757j ]
  [-0.0238499 +0.6315944j  -0.82000685+0.4485173j
    1.0157832 -0.35993174j ...  1.2199112 +0.42878163j
   -0.6004822 -0.4956446j   1.3211037 -0.66880095j]]

 [[-0.02049661-0.72674394j -0.4275315 -0.02938

(config 0 | channel CDL-E-150-1 | 5.0 dB | slot 15 | Sample: 20/164:   1%|          | 19/3444 [00:22<41:26,  1.38it/s]

tf.Tensor(
[[[-0.38164774+0.3388898j   0.61453074-0.28083402j
    0.6270234 -0.9084382j  ...  0.3830737 -1.1593559j
    0.8656792 +0.19949365j -0.9629071 -0.4060988j ]
  [-1.2825043 +0.71303874j  0.630626  +0.27258444j
    1.7073824 -0.3775771j  ...  0.16480607+1.4617159j
   -0.66361773+0.23556685j  0.5807021 +0.9858967j ]
  [ 0.59594095-0.389167j   -0.6156286 +0.695138j
   -0.9851854 +1.11795j    ... -0.47179154+0.1316275j
    1.4778349 -0.4822361j   0.33626768+0.5270399j ]
  ...
  [-1.3269744 -1.1105154j  -0.6697666 -0.21333914j
    1.1647863 +1.1986682j  ... -0.19540766-0.56457907j
   -1.2321074 -0.05798244j -0.07953541+0.32881486j]
  [ 1.0991373 -1.1678939j   0.03308612+0.53572726j
   -1.0199566 -1.342843j   ... -1.3996434 +1.0374708j
    0.4633466 +1.2596513j  -0.7356507 -0.501845j  ]
  [ 0.30616793+0.08900321j -0.5333794 -0.84587896j
   -0.7525913 +0.46911824j ... -0.38929296+0.6507729j
    1.1582718 +0.05958885j -0.7455156 -0.0165478j ]]

 [[-1.1831644 +0.6951265j   1.3376834 -0

(config 0 | channel CDL-E-150-1 | 5.0 dB | slot 4 | Sample: 21/164:   1%|          | 20/3444 [00:23<40:42,  1.40it/s] 

tf.Tensor(
[[[-0.8811077 +8.01854730e-01j  0.6184618 +1.41297460e+00j
    0.94836307-3.19510877e-01j ... -0.6230508 +1.16830468e-01j
    0.5565606 +8.01666915e-01j -1.0715017 -1.31001627e+00j]
  [ 0.6304081 +8.81270230e-01j  0.86646765-5.60135067e-01j
    0.6029705 +1.07178760e+00j ...  0.49950328-1.16407871e+00j
    0.8299088 -9.09575760e-01j -0.60006243+1.10271621e+00j]
  [ 0.5594255 -7.81605005e-01j -0.90345895+1.06059134e-01j
   -0.01149559+5.78061461e-01j ...  0.96648365+9.00298655e-02j
   -0.51245314+1.15802896e+00j  0.5012241 -2.39552081e-01j]
  ...
  [-1.3632681 +6.02664232e-01j  0.36793804+3.19439769e-02j
    0.8313089 +1.17450988e+00j ... -0.5562719 -1.77487493e-01j
    0.57899904-8.05760026e-01j  0.17823756+6.18932024e-02j]
  [ 1.3408575 -6.26903355e-01j -0.49626982+7.78987050e-01j
   -0.89098763+9.66965437e-01j ... -0.35217038+3.86676639e-01j
    0.8045981 -1.23530066e+00j  0.8764122 +4.67684269e-01j]
  [ 0.42849454+4.87053484e-01j  1.2842057 +7.92115927e-03j
    0.7984069 

(config 0 | channel CDL-E-150-1 | 5.0 dB | slot 4 | Sample: 21/164:   1%|          | 20/3444 [00:23<1:08:12,  1.20s/it]


KeyboardInterrupt: 

In [17]:
# data_dir = '/content/dataset' # if colab
data_dir = '../Pusch_data/dataset' # if workspace
name = datetime.now().strftime("%Y%m%d%H%M%S%f")
start = time.time()
df = generate_data(name=f'{name}',
              data_dir=data_dir,
              pusch_configs=[pusch_273, *pusch_config_273RB],
              channel_scenarios=[
                  'CDL-A-150-1',
                  'CDL-B-150-1',
                  'CDL-C-150-1',
                  'CDL-D-150-1',
                  'CDL-E-150-1',
                  'CDL-A-10-10',
                  'CDL-B-10-10',
                  'CDL-C-10-10',
                  'CDL-D-10-10',
                  'CDL-E-10-10',
                  'CDL-A-50-4',
                  'CDL-B-50-4',
                  'CDL-C-50-4',
                  'CDL-D-50-4',
                  'CDL-E-50-4'
                  ],
              esno_dbs=[i for i in np.arange(5.,-5.1,-0.5)],
              slots=[
                  4,
                  5,
                  14,
                  15
                  ],
              save_dataset=None
)
duration = time.time() - start

Generating Data:   0%|          | 0/3444 [00:05<?, ?it/s]


KeyboardInterrupt: 

In [61]:
# !cp /content/dataset/parquet/{name}.parquet /content/drive/MyDrive/Pusch_data/dataset/parquet
# !cp /content/dataset/hdf5/{name}.hdf5 /content/drive/MyDrive/Pusch_data/dataset/hdf5

In [16]:
assert False

AssertionError: 

In [ ]:
# !du -sh /content/dataset/pickle/20250304165249747666

129M	/content/dataset/pickle/20250304165249747666


In [ ]:
# !du -sh /content/dataset/hdf5/20250304171421232817.hdf5

113M	/content/dataset/hdf5/20250304171421232817.hdf5


In [27]:
def load_hdf5(parent_name, group_name):
    with h5py.File(f'{parent_name}.hdf5', "r") as f:
        b = f[f"{group_name}_b"][:]
        c = f[f"{group_name}_c"][:]
        y = f[f"{group_name}_y"][:]
    return b, c, y

def load_pickle(parent_name, group_name):
    """Saves data to a pickle file."""
    def load_from_pickle(filename):
        with open(filename, "rb") as f:
            return pickle.load(f)

    b = load_from_pickle(f'{parent_name}/{group_name}.b.pkl')
    c = load_from_pickle(f'{parent_name}/{group_name}.c.pkl')
    y = load_from_pickle(f'{parent_name}/{group_name}.y.pkl')

    return b, c, y

In [ ]:
def abc():
    df = pd.read_parquet('/content/dataset/parquet/20250304171421232817.parquet', engine='pyarrow')
    for n, row in enumerate(df.itertuples(index=False)):
        data_filename = row.Data_filename
        data_dirname = row.Data_dirname
        b, c, y = load_hdf5(f'/content/dataset/hdf5/{data_dirname}', data_filename)
        if n % 1000 == 0: print(b.shape, b.dtype, c.shape, c.dtype, y.shape, y.dtype)
# %timeit abc()

(288,) uint8 (1152,) uint8 (8, 14, 48) complex64
(288,) uint8 (1152,) uint8 (8, 14, 48) complex64
(288,) uint8 (1152,) uint8 (8, 14, 48) complex64
(288,) uint8 (1152,) uint8 (8, 14, 48) complex64
(288,) uint8 (1152,) uint8 (8, 14, 48) complex64
(288,) uint8 (1152,) uint8 (8, 14, 48) complex64
(288,) uint8 (1152,) uint8 (8, 14, 48) complex64
(288,) uint8 (1152,) uint8 (8, 14, 48) complex64
(288,) uint8 (1152,) uint8 (8, 14, 48) complex64
(288,) uint8 (1152,) uint8 (8, 14, 48) complex64
(288,) uint8 (1152,) uint8 (8, 14, 48) complex64
(288,) uint8 (1152,) uint8 (8, 14, 48) complex64
(288,) uint8 (1152,) uint8 (8, 14, 48) complex64
(288,) uint8 (1152,) uint8 (8, 14, 48) complex64
(288,) uint8 (1152,) uint8 (8, 14, 48) complex64
(288,) uint8 (1152,) uint8 (8, 14, 48) complex64
(288,) uint8 (1152,) uint8 (8, 14, 48) complex64
(288,) uint8 (1152,) uint8 (8, 14, 48) complex64
(288,) uint8 (1152,) uint8 (8, 14, 48) complex64
(288,) uint8 (1152,) uint8 (8, 14, 48) complex64
(288,) uint8 (1152,)

In [ ]:
def bcd():
    df = pd.read_parquet('/content/dataset/parquet/20250304165249747666.parquet', engine='pyarrow')
    for n, row in enumerate(df.itertuples(index=False)):
        data_filename = row.Data_filename
        data_dirname = row.Data_dirname
        b, c, y = load_pickle(f'/content/dataset/hdf5/{data_dirname}', data_filename)
        if n % 1000 == 0: print(b.shape, b.dtype, c.shape, c.dtype, y.shape, y.dtype)
# %timeit abc()

(288,) uint8 (1152,) uint8 (8, 14, 48) complex64
(288,) uint8 (1152,) uint8 (8, 14, 48) complex64
(288,) uint8 (1152,) uint8 (8, 14, 48) complex64
(288,) uint8 (1152,) uint8 (8, 14, 48) complex64
(288,) uint8 (1152,) uint8 (8, 14, 48) complex64
(288,) uint8 (1152,) uint8 (8, 14, 48) complex64
(288,) uint8 (1152,) uint8 (8, 14, 48) complex64
(288,) uint8 (1152,) uint8 (8, 14, 48) complex64
(288,) uint8 (1152,) uint8 (8, 14, 48) complex64
(288,) uint8 (1152,) uint8 (8, 14, 48) complex64
(288,) uint8 (1152,) uint8 (8, 14, 48) complex64
(288,) uint8 (1152,) uint8 (8, 14, 48) complex64
(288,) uint8 (1152,) uint8 (8, 14, 48) complex64
(288,) uint8 (1152,) uint8 (8, 14, 48) complex64
(288,) uint8 (1152,) uint8 (8, 14, 48) complex64
(288,) uint8 (1152,) uint8 (8, 14, 48) complex64
(288,) uint8 (1152,) uint8 (8, 14, 48) complex64
(288,) uint8 (1152,) uint8 (8, 14, 48) complex64
(288,) uint8 (1152,) uint8 (8, 14, 48) complex64
(288,) uint8 (1152,) uint8 (8, 14, 48) complex64
(288,) uint8 (1152,)

In [ ]:
# %timeit !cp /content/dataset/hdf5/20250304171421232817.hdf5 /content/drive/MyDrive/Pusch_data/dataset/hdf5


1.34 s ± 379 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [ ]:
# start = time.time()
# !cp -r /content/dataset/pickle/20250304165249747666 /content/drive/MyDrive/Pusch_data/dataset/pickle
# duration = time.time() - start
# duration

94.83374857902527

In [ ]:
# start = time.time()
# !cp -r /content/drive/MyDrive/Pusch_data/dataset/pickle/20250304165249747666 /content/dataset_copy/pickle
# duration = time.time() - start
# duration

272.0682830810547

In [ ]:
# %timeit !cp /content/drive/MyDrive/Pusch_data/dataset/hdf5/20250304171421232817.hdf5 /content/dataset_copy/hdf5

The slowest run took 9.36 times longer than the fastest. This could mean that an intermediate result is being cached.
1.2 s ± 1.44 s per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [ ]:
# assert False

In [ ]:
# !cp /content/drive/MyDrive/Pusch_data/dataset/parquet/20250304181811698207.parquet /content/dataset/parquet

In [ ]:
# !cp /content/drive/MyDrive/Pusch_data/dataset/hdf5/20250304181811698207.hdf5 /content/dataset/hdf5

In [ ]:
# !gdown --folder --id 1-D1FSox1TpjKW59wPqpZvbH1b3Tcghk6 -O /content/abc

/usr/local/lib/python3.11/dist-packages/gdown/__main__.py:140: FutureWarning: Option `--id` was deprecated in version 4.3.1 and will be removed in 5.0. You don't need to pass it anymore to use a file ID.
  warnings.warn(
Retrieving folder contents
Processing file 1-Qpl2BqeVPY75whKPPx8ePn__8PoCWc7 20250304171421232817.hdf5
Processing file 1FxvsTX-bYFQHFMk6r4Vrx0tl7vBnOVC2 20250304181811698207.hdf5
Retrieving folder contents completed
Building directory structure
Building directory structure completed
Downloading...
From (original): https://drive.google.com/uc?id=1-Qpl2BqeVPY75whKPPx8ePn__8PoCWc7
From (redirected): https://drive.google.com/uc?id=1-Qpl2BqeVPY75whKPPx8ePn__8PoCWc7&confirm=t&uuid=5939bbc5-ad30-429c-899a-960d9f7081fb
To: /content/abc/20250304171421232817.hdf5
100% 118M/118M [00:01<00:00, 74.6MB/s]
Downloading...
From (original): https://drive.google.com/uc?id=1FxvsTX-bYFQHFMk6r4Vrx0tl7vBnOVC2
From (redirected): https://drive.google.com/uc?id=1FxvsTX-bYFQHFMk6r4Vrx0tl7vBnOVC2

In [ ]:
# df = pd.read_parquet('/content/dataset/parquet/20250304181811698207.parquet', engine='pyarrow')

In [ ]:
# df = pd.read_parquet('/content/dataset/parquet/20250304181811698207.parquet', engine='pyarrow')
# for n, row in enumerate(df.itertuples(index=False)):
#     data_filename = row.Data_filename
#     data_dirname = row.Data_dirname
#     b, c, y = load_hdf5(f'/content/dataset/hdf5/{data_dirname}', data_filename)
#     if n % 1000 == 0: print(b.shape, b.dtype, c.shape, c.dtype, y.shape, y.dtype)

(19464,) uint8 (78624,) uint8 (8, 14, 3276) complex64
(19464,) uint8 (78624,) uint8 (8, 14, 3276) complex64
(19464,) uint8 (78624,) uint8 (8, 14, 3276) complex64


NameError: name 'start' is not defined